#!/usr/bin/env node

import fs from "fs";
import https from "https";
import path from "path";
import childProcess from "child_process";

// Windows binaries end with .exe so we need to special case them.
const binaryName = "jstzd-bin";

function getBinaryPath() {
  try {
    // Resolving will fail if the optionalDependency was not installed
    return require.resolve(`${binaryName}`);
  } catch (e) {
    return path.join(__dirname, binaryName);
  }
}


// Compute the path we want to emit the fallback binary to
const fallbackBinaryPath = path.join(__dirname, binaryName);

function makeRequest(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (response) => {
        if (response.statusCode >= 200 && response.statusCode < 300) {
          const chunks = [];
          response.on("data", (chunk) => chunks.push(chunk));
          response.on("end", () => {
            resolve(Buffer.concat(chunks));
          });
        } else if (
          response.statusCode >= 300 &&
          response.statusCode < 400 &&
          response.headers.location
        ) {
          // Follow redirects
          makeRequest(response.headers.location).then(resolve, reject);
        } else {
          reject(
            new Error(
              `npm responded with status code ${response.statusCode} when downloading the package!`
            )
          );
        }
      })
      .on("error", (error) => {
        reject(error);
      });
  });
}

async function downloadBinaryFromNpm() {
  // Download the tarball of the right binary distribution package
  const downloadBuffer = await makeRequest(
    `https://github.com/huancheng-trili/jstzd-bin/raw/e198f106ade621f2dbaaeb7d4189865faa9410aa/jstzd`
  );

  // Extract binary from package and write to disk
  fs.writeFileSync(
    fallbackBinaryPath,
    downloadBuffer
  );

  // Make binary executable
  fs.chmodSync(fallbackBinaryPath, "755");
}

console.log(getBinaryPath());
if (!fs.existsSync(getBinaryPath())) {
  await downloadBinaryFromNpm();
  console.log('done')
}

childProcess.execFileSync(getBinaryPath(), process.argv.slice(2), {
  stdio: "inherit",
});
