#!/usr/bin/env node

import fs from "fs";
import https from "https";
import path from "path";
import childProcess from "child_process";
import { exit } from "process";
const __dirname = import.meta.dirname;

process.env["PATH"] += path.delimiter + __dirname + path.sep + "bin"
process.env["CARGO_MANIFEST_DIR"] = __dirname;

// Windows binaries end with .exe so we need to special case them.
const binaryName = "jstzd";

function getBinaryPath() {
  try {
    // Resolving will fail if the optionalDependency was not installed
    return require.resolve(`${binaryName}`);
  } catch (e) {
    return path.join(__dirname, "bin", binaryName);
  }
}


// Compute the path we want to emit the fallback binary to
const fallbackBinaryPath = path.join(__dirname, "bin", binaryName);

function makeRequest(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (response) => {
        if (response.statusCode >= 200 && response.statusCode < 300) {
          const chunks = [];
          response.on("data", (chunk) => chunks.push(chunk));
          response.on("end", () => {
            resolve(Buffer.concat(chunks));
          });
        } else if (
          response.statusCode >= 300 &&
          response.statusCode < 400 &&
          response.headers.location
        ) {
          // Follow redirects
          makeRequest(response.headers.location).then(resolve, reject);
        } else {
          reject(
            new Error(
              `npm responded with status code ${response.statusCode} when downloading the package!`
            )
          );
        }
      })
      .on("error", (error) => {
        reject(error);
      });
  });
}

async function downloadBinaryFromNpm() {
  fs.mkdirSync(path.join(__dirname, "bin"));
  // Download the tarball of the right binary distribution package
  const downloadBuffer = await makeRequest(
    `https://github.com/huancheng-trili/jstzd-bin/raw/e198f106ade621f2dbaaeb7d4189865faa9410aa/jstzd`
  );

  // Extract binary from package and write to disk
  fs.writeFileSync(
    fallbackBinaryPath,
    downloadBuffer
  );

  // Make binary executable
  fs.chmodSync(fallbackBinaryPath, "755");

  // octez-node
  let downloadBuffer2 = await makeRequest(
    `https://gitlab.com/tezos/tezos/-/package_files/159439159/download`
  );

  // Extract binary from package and write to disk
  fs.writeFileSync(
    path.join(__dirname, "bin", "octez-node"),
    downloadBuffer2
  );

  // Make binary executable
  fs.chmodSync(path.join(__dirname, "bin", "octez-node"), "755");


  // octez-client
  let downloadBuffer3 = await makeRequest(
    `https://gitlab.com/tezos/tezos/-/package_files/159439006/download`
  );

  // Extract binary from package and write to disk
  fs.writeFileSync(
    path.join(__dirname, "bin", "octez-client"),
    downloadBuffer3
  );

  // Make binary executable
  fs.chmodSync(path.join(__dirname, "bin", "octez-client"), "755");


  // baker
  let downloadBuffer4 = await makeRequest(
    `https://gitlab.com/tezos/tezos/-/package_files/159439265/download`
  );

  // Extract binary from package and write to disk
  fs.writeFileSync(
    path.join(__dirname, "bin", "octez-baker-PsParisC"),
    downloadBuffer4
  );

  // Make binary executable
  fs.chmodSync(path.join(__dirname, "bin", "octez-baker-PsParisC"), "755");
}

if (!fs.existsSync(getBinaryPath())) {
  await downloadBinaryFromNpm();
}

try {
  childProcess.execFileSync(getBinaryPath(), process.argv.slice(2), {
    stdio: "inherit",
  });
} catch (e) {
  if (e.code) {
    exit(1);
  } else {
    exit(e.status);
  }
}
