#!/usr/bin/env node

import { promises as fs } from 'fs';
import https from "https";
import path from "path";
import childProcess from "child_process";
import { exit } from "process";
const __dirname = import.meta.dirname;

process.env["PATH"] += path.delimiter + __dirname + path.sep + "bin"
process.env["CARGO_MANIFEST_DIR"] = __dirname;

// Windows binaries end with .exe so we need to special case them.
const binaryName = "jstzd";

function getBinaryPath() {
  try {
    // Resolving will fail if the optionalDependency was not installed
    return require.resolve(`${binaryName}`);
  } catch (e) {
    return path.join(__dirname, "bin", binaryName);
  }
}


// Compute the path we want to emit the fallback binary to
const fallbackBinaryPath = path.join(__dirname, "bin", binaryName);

function makeRequest(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (response) => {
        if (response.statusCode >= 200 && response.statusCode < 300) {
          const chunks = [];
          response.on("data", (chunk) => chunks.push(chunk));
          response.on("end", () => {
            resolve(Buffer.concat(chunks));
          });
        } else if (
          response.statusCode >= 300 &&
          response.statusCode < 400 &&
          response.headers.location
        ) {
          // Follow redirects
          makeRequest(response.headers.location).then(resolve, reject);
        } else {
          reject(
            new Error(
              `npm responded with status code ${response.statusCode} when downloading the package!`
            )
          );
        }
      })
      .on("error", (error) => {
        reject(error);
      });
  });
}

async function downloadBin(url, dst) {
  const downloadBuffer = await makeRequest(url);

  // Extract binary from package and write to disk
  await fs.writeFile(
    dst,
    downloadBuffer
  );

  // Make binary executable
  await fs.chmod(dst, "755");
}

async function downloadBinaryFromNpm() {
  await fs.mkdir(path.join(__dirname, "bin"));
  // Download the tarball of the right binary distribution package

  await Promise.all([
    downloadBin("https://github.com/huancheng-trili/jstzd-bin/raw/377f11108bc9f44a203c2acc7f95e7541f4f7a27/jstzd", fallbackBinaryPath),
    downloadBin("https://gitlab.com/tezos/tezos/-/package_files/159439159/download", path.join(__dirname, "bin", "octez-node")),
    downloadBin("https://gitlab.com/tezos/tezos/-/package_files/159439006/download", path.join(__dirname, "bin", "octez-client")),
    downloadBin("https://gitlab.com/tezos/tezos/-/package_files/159439265/download", path.join(__dirname, "bin", "octez-baker-PsParisC")),
  ]);
}

if (!await fs.exists(getBinaryPath())) {
  await downloadBinaryFromNpm();
}

try {
  childProcess.execFileSync(getBinaryPath(), process.argv.slice(2), {
    stdio: "inherit",
  });
} catch (e) {
  if (e.code) {
    exit(1);
  } else {
    exit(e.status);
  }
}
